"""adiciona software_name e torna cnpj obrigatorio

Revision ID: 8f63168ec484
Revises: f316bdc14c85
Create Date: 2026-08-13 12:05:09.092141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f63168ec484'
down_revision: Union[str, Sequence[str], None] = 'f316bdc14c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('software_name', sa.String(), nullable=True))
    op.alter_column('companies', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'software_name')
    # ### end Alembic commands ###
